version: '3.2'

volumes:
    app:
        driver_opts:
            type: none
            o: bind
            device: ":${PWD}/${SYMFONY_APP_PATH}"

    web:
        driver_opts:
            type: none
            o: bind
            device: ":${PWD}/${WEB_PATH}"
